# Generated by Django 4.2.6 on 2023-10-13 08:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('masonryimage', models.ImageField(upload_to='uploads/')),
                ('fullview', models.CharField(default='col-lg-3', max_length=225)),
                ('title', models.CharField(max_length=225)),
                ('shortdesc', models.CharField(max_length=225)),
                ('postdate', models.CharField(max_length=225)),
                ('authorname', models.CharField(max_length=50)),
                ('longdescription', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
        ),
    ]
