# Generated by Django 4.2.6 on 2023-10-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_id_blogpost_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='Category',
            field=models.CharField(default='uradgota', max_length=225),
        ),
    ]
