# Generated by Django 4.2.6 on 2023-12-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blogpost_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=225)),
                ('Image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
