# Generated by Django 4.2.6 on 2024-01-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_indusdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indusdata',
            name='Message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='indusdata',
            name='Phonenumber',
            field=models.CharField(max_length=50),
        ),
    ]
