# Generated by Django 4.2.6 on 2024-01-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_indusdata_message_alter_indusdata_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='SliderId',
            field=models.IntegerField(default=0),
        ),
    ]
