# Generated by Django 4.1 on 2024-01-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_banner_sliderid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('Products_id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Short_desc', models.CharField(max_length=200)),
                ('Long_desc', models.CharField(max_length=1000)),
                ('Upload_url', models.URLField(default='')),
                ('Body', models.CharField(max_length=150)),
                ('Slug', models.CharField(max_length=200, null=True, unique=True)),
                ('Image1', models.ImageField(upload_to='uploads/')),
                ('Image2', models.ImageField(upload_to='uploads/')),
                ('Image3', models.ImageField(upload_to='uploads/')),
                ('Image4', models.ImageField(upload_to='uploads/')),
                ('Image5', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
