# Generated by Django 4.1 on 2024-01-24 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_productsinfo_alter_products_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsinfo',
            old_name='Slug',
            new_name='Sluglink',
        ),
    ]
