# Generated by Django 4.1 on 2024-01-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_slug_productsinfo_sluglink'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsinfo',
            name='category',
            field=models.CharField(choices=[('Consumer_packs', 'Consumer_packs'), ('Commercial_packs', 'Commercial_packs')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productsinfo',
            name='Products_id',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
    ]
