# Generated by Django 4.1 on 2024-01-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_productsinfo_category_alter_productsinfo_products_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductsInfo',
        ),
        migrations.AddField(
            model_name='products',
            name='Product_type',
            field=models.CharField(choices=[('Consumer_pack', 'Consumer_pack'), ('Commercial_pack', 'Commercial_pack')], default='', max_length=200, null=True),
        ),
    ]
