# Generated by Django 4.1 on 2024-01-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_productsinfo_products_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=50)),
                ('Phonenumber', models.CharField(max_length=10)),
                ('Purpose', models.CharField(max_length=100)),
                ('Subject', models.CharField(max_length=500)),
                ('Message', models.CharField(max_length=1000)),
            ],
        ),
    ]
