# Generated by Django 4.1 on 2024-01-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Related_products',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
